# Save as docker-compose-windows.yml
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: context-keeper-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      # Use named volumes instead of bind mounts
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped

  neo4j:
    image: neo4j:5-community
    container_name: context-keeper-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/contextkeeper2024
      - NEO4J_PLUGINS=["apoc"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: context-keeper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: context-keeper-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

# Define named volumes (Docker manages these)
volumes:
  qdrant_storage:
  neo4j_data:
  neo4j_logs:
  redis_data:
  ollama_data:

networks:
  default:
    name: context-keeper-network